### ISSUE TITLE
Vertaisarvio

### ISSUE THREAD

**Issue by Doubleneck** [katriryt/Tiralabra-2022-VerbumReprehendo#1]
Ladattu: 14.8.  klo 21.17

1. Työ näyttäisi olevan hyvällä mallilla, ja kaikki aukesi ja tuntuu toimivan (MacOS). Käytön hahmottaminen oli hieman hankalaa, kun käyttöohjetta ei vielä ollut, mutta sitä ei myöskään tässä vaiheessa muistaakseni vaadittu.  

Yleisesti ottaen hyvin tehdyltä vaikuttaa, luokat on järkeviä, testaaminen pitkällä, jne. On ilo yrittää saada tolkkua itselle vieraasta aiheesta, kun muuttujat, metodit ja luokat on nimetty informatiivisesti, siitä iso kiitos! 

Varsinaisesta algoritmiikasta näyttäisi toimivan tässä vaiheessa vain Damerau-Levenshtein. 

2. Trie-luokka:

Mahdollinen parannusehdotus tehostamaan algoritmia:
Olettaisin, että hyvä paikka koettaa tehostaa toimintaa, olisi rajata Trie-puuta jollain tavalla. Nyt siinä haetaan get_all_words -metodissa kaikki sanat. Kokeilin nopeasti, miten se toimisi, jos rajoittaisi sen olettamaan, että alkukirjain on aina oikea. 
Eli käytäisiin virheellisesti kirjoitetun sanan bboy kohdalla vain b-alkuiset sanat. Nopeutuu tietenkin aika rajusti.

Et välttämättä tietenkään halua tehdä juuri tätä optimointia, tässähän menetetään osa vaihtoehdoista, mutta nopeuden muutos on suuri, kun kaikkia alkukirjaimia ei käydä läpi. 

Mä en varmasti tajunnut kaikkia elementtejä joita tässä työssä tulee olemaan, jotka saattaa tehdä tästä optimoinnista hankalan.
Jostakin tuolta se rajoittaminen ehkä kuitenkin tehokkaasti löytyy?

3. Testi-luokassa on joitakin pikkujuttuja:

Esim. spell_check_test.py -luokassa kaikki testit ovat tyyppiä AssertEqual. Tässähän ei ole mitään vikaa, pytestissä on kuitenkin paljon erilaisia assertioita, joilla saa testikoodia tymäkämmäksi. Esim AssertNotEqual voi tuntua mielekkäämmältä joskus.

https://kapeli.com/cheat_sheets/Python_unittest_Assertions.docset/Contents/Resources/Documents/index 

3.1 Testeissä on kautta linjan vähän turhia muuttujia:

def test_search_word_full_data_false(self):
        word_tested = "word_not_found"
        output = self.test_trie.search_word_full_data(word_tested)
        wanted_answer = False
        self.assertEqual(output, wanted_answer)
        
Voisi olla lyhyemmin vaikkapa:

def test_search_word_full_data_false(self):
        word_tested = "word_not_found"
        output = self.test_trie.search_word_full_data(word_tested)
        self.assertNotEqual(output, True)
        
 3.2 Pari testeistä on hieman erikoisia (vaikka tavallaan testaavatkin ihan oikeaa asiaa) sikäli, että esim "user_word" on tässä sellainen, mitä user ei voi antaa syötteen rajauksen takia:
 
   def test_calculate_optimal_string_alignment_distance(self):
        test_user_word = "a_cat"
        test_dictionary_word = "an_act"
        output = self.check_spelling.calculate_optimal_string_alignment_distance(
            test_user_word, test_dictionary_word)
        wanted_answer = 2
        self.assertEqual(output, wanted_answer)

    def test_calculate_damerau_levenshtein_distance(self):
        test_user_word = "a_cat"
        test_dictionary_word = "an_act"
        output = self.check_spelling.calculate_damerau_levenshtein_distance(
            test_user_word, test_dictionary_word)
        wanted_answer = 2
        self.assertEqual(output, wanted_answer)
        
 4. Aika mitätön pikkujuttu, mutta UI-luokan docstringssissä:
 
 class UI:
    """Class starts the application and provides methods for interacting
    with the user.
    """
    
  Oikeastaanhan index.py käynnistää sovelluksen, ei UI? 
  No tää oli jo aika onneton korjausehdotus :)
  
5. Hattu nousee, ei olla menty sieltä missä aita on matalin, vaan perehdytty ja pyritty saamaan aikaan selkeä ja toimiva kokonaisuus. Tsemppiä maaliin viemiseksi!

**Comment by katriryt** [comment]
Kiitokset laadukkaasta vertaisarvioinnista! Oli hienoa, että sovellus tuli testattua MacOS:ssäkin.

Palautteesi mukaisesti hioin hieman ui:ta sekä lisäsin käyttöohjeen, että sovellusta olisi helpompi ymmärtää ja käyttää. Kiitokset hyvistä vinkeistä testien osalta! Hioin testejä palautteesi perusteella selkeämmiksi. Samoin tarkensin ui:n docstringiä. Parannusehdotus algoritmin tehostamisesta oli erinomainen. Jätin sen projektin tuleviin parannusvaiheisiin, koska työn fokuksessa ei ollut löytää erityisen tehokasta algoritmia nopeuden kannalta. 

Kiitokset avustasi sovelluksen kanssa!
