### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by JonathanHeyno** [katriryt/Tiralabra-2022-VerbumReprehendo#2]
Ladattu 21.8. klo. 18:20

1)

Tehtävään ja eri asiaan kuuluviin algoritmeihin on perehdytty syvällisesti. Ongelmaa ratkotaan kattavasti monella eri algoritmilla

2)

Kuten projektidokumentaatiossa on jo todettu, WordNetistä puuttuu joitain sanoja ja sanojen eri muotoja, kuten menneitä aikamuotoja. Olisi hyvä jos käyttöliittymä sallii hypätä sanan korjauksen yli, eli kun se kysyy

```Would you like to use more advanced methods (weighting distance metrics) to identify your word? Press 1 if yes, and 2 if no:```

Voisi lisätä vaihtoehdon ”3: Skip”, koska käyttäjä tietää että sana on kuitenkin oikein, niin ohjelma ei lähtisi hakemaan ”korjattua” sanaa.

3)

Nähdäkseni isoin ongelma tässä on se että WordNetistä puuttuu paljon sanoja (eri sanamuodot ja muutama keskeinen sana). Tämä lähinnä kai siksi ettei WordNettiä ole vissiin tarkoitettu oikeastaan tähän, vaan hieman muuhun. Tässä projektissa ei kuitenkaan ilmeisesti tarvita kuin raaka lista englanninkielisiä sanoja joten voisi käyttää jotain muuta, laajempaa sanakirjaa. Esim. tässä on yli 466k sanaa ml. eri taivutusmuotoja ja sanat ”the”, ”it”, jne.

https://raw.githubusercontent.com/dwyl/english-words/master/words.txt

Tästä löytyy ko. listaan liittyen lähdetietoa ja ehkä tietoja lisensseistä jos niitä haluaa ihmetellä:

https://github.com/dwyl/english-words

Jos tuota listaa ei halua käyttää, voi esim. prujata nltk-kirjaston sanat (ei ihan yhtä kattava mutta sisältää kuitenkin 236k sanaa):

pip install nltk

Sitte pythonissa:

import nltk
nltk.download('words')
from nltk.corpus import words
f = open("words.txt", "w")
for word in words.words():
    f.write(word)
    f.write('\n')
f.close()

Jos ei jaksa uudestaan hakea noiden sanojen frekvenssit BNC:stä, voisi esim. yksinkertaisesti liittää uudet sanat olemassa olevaan frekvenssilistaan kaikki frekvenssillä 1. Frekvenssit ovat silloin tietenkin kaikilla 1, mutta ohjelma ei ainakaan herjaa oikein kirjoitetuista sanoista joista se nyt valittaa.

4)

Tämä nyt on oikeastaan enemmänkin huomio kuin mikään korjausehdotus, mutta hyvä tietenkin pitää mielessä. Ilmeisesti WordNetissä (kuten noissa kahdessa muussakin listaamassani sanalistassa) on sanojen brittiläiset muodot ja amerikkalaiset muodot, mikä on hienoa. Samoin BNC korpukseenkin on vuosikymmenien saatossa ilmeisesti eksynyt sanoista kumpiakin muotoja. Kuitenkin hyvä pitää mielessä frekvenssien suhteen että BNC:ssä on tietenkin sanojen brittiversioista huomattavan paljon suurempi frekvenssi kuin amerikkalaisista. Esim. brittiläisittäin sanasta ”colour” on frekvenssi 11800, kun taas amerikkalaisesta versiosta ”color” on frekvenssi 116. Ei siis mitenkään ongelma, mutta varmaan mielenkiintoinen huomio.

Top suggestions for your word coolor are:
Word: color, distance: 1.00, frequency: 116
Word: colour, distance: 1.33, frequency: 11800

5)

Muuten koodi on selkeää ja siistiä. Metodit ja muuttujat on nimetty järkevästi ja kommentointi on kattavaa.

**Comment by katriryt** [comment]
Kiitokset laadukkaasta vertaisarvioinnista! 

Tein ehdotuksesi mukaisesti muutoksia ui:n, eli sovellus tarkstaa nyt sanan korjauksen yli hyppäämisen. Sovelluksen pohjalla olevaa sanakirjaa en tässä vaiheessa työtä lähtenyt vaihtamaan (ymmärtääkseni valmiita tarjolla olevia paketteja ei ollut tarkoitus käyttää), mutta huomio ja ideat olivat erinomaisia.

Kiitokset avustasi sovelluksen kanssa!
